name: 🐛 Bug Report
description: Create a report to help us reproduce and fix the bug
labels: 'bug'

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting a bug, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/epwalsh/obsidian.nvim/issues?q=is%3Aissue+sort%3Acreated-desc+).
- type: textarea
  attributes:
    label: 🐛 Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a minimal example or configuration so that we can reproduce the error by running the code. It is very important for the snippet to be as succinct (minimal) as possible, so please take time to trim down any irrelevant code to help us debug efficiently. We are going to copy-paste your code and we expect to get the same result as you did: avoid any external data, and include the relevant imports, etc. For example:

      ```lua
      -- All necessary imports at the beginning
      require "obsidian"

      -- A succinct reproducing example trimmed down to the essential parts:
      error("Oh no!")
      ```

      Please also paste or describe the results you observe instead of the expected results. If you observe an error (check `:messages` and/or `:Noice`), please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in a ```` ```triple quotes code block``` ````.
    placeholder: |
      A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Config
    description: |
      Please paste your obsidian.nvim config below, wrapped in a ```` ```triple quotes code block``` ````.
    placeholder: |
      Your config wrapped in a triple quotes code block  ``` ... ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Please run the following and paste the output below, wrapped in a ```` ```triple quotes code block``` ````.
      
      ```sh
      nvim --version
      nvim --headless -c 'lua require("obsidian").info()' -c q
      ```

      Note that you'll have to ensure obsidian.nvim loads up front for that command to be able to gather all of the information it needs, which means ensuring your plugin manager does not load obsidian.nvim lazily.
    placeholder: |
      Output wrapped in a triple quotes code block ``` ... ```
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
